<%
TituloPagina = "Matrículas satisfactorias";
MatriculaAprobada = "Matrícula aprobada: ";
MatModAcademica = "Su matrícula a la modalidad académica ";
HaSidoAceptada = " ha sido aceptada.";
GraciasPorSuInteres = "  Gracias por su interés";
Mensaje = "Este mensaje ha sido generado automáticamente por el SEPAD cuando el coordinador de la modalidad aceptó la matrícula solicitada por usted. Si considera que es un error contacte con el claustro de la modalidad académica ";
%>
