<%
var TituloPagina = "Arbol";
var Expan = "Expandir";
var Contr = "Contraer";
var AAlumno = "Adicionar alumno";
var AGrupoAlumno = "Adicionar alumnos de un grupo";
var SolicitudesMat = "Solicitudes de matrículas";
var DesignarProfesor = "Designar profesor";
var DesignarGrupoProfesores = "Designar profesores de un grupo";
var ModVerEliminar = "Módulos(Ver/Eliminar)";
var AlumVerEliminar = "Alumnado(Ver/Eliminar)";
var ClaustroVerEliminar = "Claustro(Ver/Eliminar)";
var GModalidadAcadem = "Generalidades de la modalidad académica";
var AModulo = "Adicionar módulo";
%>