<%
 SolicitudesBaja = "Las solicitudes fueron eliminadas satisfactoriamente.";
 MatriculaDenegada = "Matrícula denegada: ";
 MatModalidadAcadem = "Su matrícula a la modalidad académica ";
 HaSidoDenegada = " ha sido denegada.";
 Mensaje = "Este mensaje ha sido generado automáticamente por el SEPAD cuando el cordinador de la modalidad denegó la matrícula solicitada por usted. Si considera que es un error contacte con el claustro de la modalidad académica ";
%>