<%
var  TXT_TILE = "Datos Generales";
var  TEXT1 = "Datos Generales";
var  TEXT2 = "Nombre y Apellidos";
var  TEXT3 = "Identificador";
var  TEXT4 = "Email";
var  TEXT5 = "Número de Identidad";
var  TEXT6 = "Fecha de Nacimiento";
var  TEXT7 = "Sexo";
var  TEXT8 = "Dirección";
var  TEXT9 = "Código Postal";
var TEXT10 = "Teléfono";
var TEXT11 = "País";
var TEXT12 = "Provincia";
var TEXT13 = "Título";
var TEXT14 = "Profesión";
var TEXT15 = "Especialidad";
var TEXT16 = "Año de graduación";
var TEXT17 = "Institución";
var TEXT18 = "Perfiles Laborales";
var TEXT19 = "Trabajo Actual";
var TEXT20 = "Cargo Actual";
var TEXT21 = "Otros";
var TEXT22 = "Perfiles Investigativos";
var TEXT23 = "Categoría Docente";
var TEXT24 = "Categoría Investigativa";
var TEXT25 = "Categoría Científica";
%>