<%
var stmp1 = "Configurar el sistema";
var stmp2 = "Configuración del servidor de base de datos";
var stmp3 = "DSN:";
var stmp4 = "por ejemplo: dsn=sepad1.2";
var stmp5 = "Tipo de servidor:";
var stmp6 = "SQL Server";
var stmp7 = "Microsoft Access";
var stmp8 = "Configuración del servicio de respuesta automática por correo a la solicitud de matrículas";
var stmp9 = "Dirección de correo:";
var stmp10 = "Usuario:";
var stmp11 = "Contraseña:";
var stmp12 = "Dirección del servidor de correo:";
var stmp13 = "Puerto:";
var stmp14 = "Autentificación:";
var stmp15 = "Sí";
var stmp16 = "No";
var stmp17 = "Asunto del mensaje de respuesta a solicitudes de registro al sistema:";
var stmp18 = "Cuerpo del mensaje de respuesta a solicitudes de registro al sistema:";
var stmp19 = "Configuración general";
var stmp20 = "Logotipo:";
var stmp21 = "Página principal:";
var stmp22 = "Página de descargas de softwares:";
var stmp23 = "Cantidad de elementos de las listas que se muestran en el sistema:";
var stmp24 = "Cantidad de días para considerar una noticia como nueva:";
var stmp25 = "Modificar";
var stmp26 = "Aceptar automáticamente todas las solicitudes de registro al sistema";
%>
