<%
var stmp1 = "Resultado de la eliminación de usuarios";
var stmp2 = "Usuario";
var stmp3 = "Resultado";
var stmp4 = "Eliminado correctamente";
var stmp5 = "No se pudo eliminar. ";
var stmp6 = "Revise el usuario no sea el coordinador de alguna modalidad académica, profesor principal de algún módulo o tutor de algún subgrupo tutoreado. Si es así elimine la modalidad, el módulo o subgrupo, o sustitúyale el coordinador, el profesor principal o el tutor según el caso que sea.";
var stmp7 = "Regresar";
%>
