<%
var title = "Prólogo del curso ";
var stmp1 = "Si está interesado en matricular este curso debe primero solicitar su matrícula en el sistema ";
var stmp2 = "Aula&nbsp;Virtual";
var stmp3 = "'CourseTutor'";
var stmp4 = "Tutorear";
var stmp5 = "'CourseAdm'";
var stmp6 = "Administrar";
var stmp7 = "Si está interesado en matricular esta modalidad académica, haga su solicitud aquí ";
var stmp8 = "'Matricular'";
var stmp9 = "Matricular.";
var stmp10 = " Si es aceptado se le hará saber mediante el correo interno del sistema. ";
var stmp11 = "Módulo: ";
var stmp12 = "Código: ";
var stmp13 = "Claustro: ";
var stmp14 = "Identificador";
var stmp15 = "Nombre y apellidos";
var stmp16 = "Correo eléctronico";
var stmp17 = "Profesor Principal";
var stmp18 = "Tutor";
var stmp19 = "Estado:";
var stmp20 = "No visible";
var stmp21 = "Deshabilitado";
var stmp22 = "En curso";
var stmp23 = "Finalizado";
var stmp24 = "Deshabilitado";
%>
