<%
var title = "Crear Anuncio";
var stmp1 = "Crear Anuncio";
var stmp2 = "Título:";
var stmp3 = "Cuerpo:";
var stmp4 = "Expira:";
var stmp5 = "Sí";
var stmp6 = "Fecha&nbsp;en&nbsp;que&nbsp;expira:";
var stmp7 = "Día:";
var stmp8 = "Mes:";
var stmp9 = "Enero";
var stmp10 = "Febrero";
var stmp11 = "Marzo";
var stmp12 = "Abril";
var stmp13 = "Mayo";
var stmp14 = "Junio";
var stmp15 = "Julio";
var stmp16 = "Agosto";
var stmp17 = "Septiembre";
var stmp18 = "Octubre";
var stmp19 = "Noviembre";
var stmp20 = "Diciembre";
var stmp21 = "Año:";
var stmp22 = "Aceptar";
%>
