<%
var SESSION_TIMEOUT_SHORT = "Se venció su tiempo de espera en el sistema.";
var SESSION_TIMEOUT_TEXT  = "Se venció su tiempo de espera en el sistema o la página fue accedida incorrectamente. La causa más frecuente de este error es permanecer más tiempo que el establecido (" + Session.Timeout + " minutos)  sin ejecutar ninguna acción. Si desea continuar vuelva a conectarse y autentificarse.";
var SEARCH_TEXT	          = "Buscar";
var PAGE_HEADER_TEXT      = "Búsqueda de Usuarios";
var SEARCH_LABEL_TEXT     = "Búsqueda por";  
var USER_LIST_TEXT        = "Listado de Usuarios";
var SEARCH_ID_TEXT        = "Identificador";
var FULL_NAME_TEXT        = "Nombre y apellidos";
var EMAIL_TEXT	          = "Correo eléctronico";

var TITLE1 = "Búsquedas de Usuarios";
var TEXT1 = "Crear";
var TEXT2 = "Eliminar";
var TEXT3 = "Seleccionar Todo";
var TEXT5 = "Identificador";
var TEXT6 = "Nombre y apellidos";
var TEXT7 = "Correo eléctronico";
var TEXT8 = "Alta";
var TEXT9 = "Último acceso";
%>